defaults: &defaults
  working_directory: ~/dysco
  shell: /bin/bash -leo pipefail
  docker:
    - image: circleci/python:3.8.0b4-buster

whitelist: &whitelist
  paths:
    - .coverage
    - .coveragerc
    - .envrc
    - .flake8
    - .isort.cfg
    - .tox
    - .venv
    - docs
    - htmlcov
    - poetry.lock
    - pyproject.toml
    - dysco
    - tests
    - tox.ini


version: 2
jobs:

  build-3.8:
    <<: *defaults
    docker:
      - image: circleci/python:3.8.0b4-buster

    steps:
      - checkout
      - restore_cache:
          keys:
            - dysco-python-3.8-{{ .Branch }}-{{ .Revision }}
            - dysco-python-3.8-{{ .Branch }}-
            - dysco-python-3.8
      - run:
          name: Install Dependencies
          no_output_timeout: 60m
          command: |
            virtualenv .venv
            . .venv/bin/activate
            pip install tox poetry==1.0.0b4
            tox -e py38-init
      - save_cache:
          key: dysco-python-3.8-{{ .Branch }}-{{ .Revision }}
          paths:
            - .tox
            - .venv

      - run:
          name: Lint
          no_output_timeout: 60m
          command: |
            . .venv/bin/activate
            tox -e py38-lint

      - run:
          name: Test
          no_output_timeout: 60m
          command: |
            . .venv/bin/activate
            tox -e py38-test
            # Used for the test coverage badge in the README.
            echo "{ \"coverage\": \"$(./.tox/py38/bin/coverage report | tail -n 1 | awk '{print $6}')\" }" > htmlcov/total-coverage.json

      - run:
          name: Docs
          no_output_timeout: 60m
          command: |
            . .venv/bin/activate
            tox -e py38-docs

      - store_artifacts:
          path: htmlcov
          destination: coverage-report

      - store_artifacts:
          path: dist/docs
          destination: documentation

  build-3.7:
    <<: *defaults
    docker:
      - image: circleci/python:3.7.5-stretch

    steps:
      - checkout
      - restore_cache:
          keys:
            - dysco-python-3.7-{{ .Branch }}-{{ .Revision }}
            - dysco-python-3.7-{{ .Branch }}-
            - dysco-python-3.7
      - run:
          name: Install Dependencies
          no_output_timeout: 60m
          command: |
            virtualenv .venv
            . .venv/bin/activate
            pip install tox poetry==1.0.0b4
            tox -e py37-init
      - save_cache:
          key: dysco-python-3.7-{{ .Branch }}-{{ .Revision }}
          paths:
            - .tox
            - .venv

      - run:
          name: Lint
          no_output_timeout: 60m
          command: |
            . .venv/bin/activate
            tox -e py37-lint

      - run:
          name: Test
          no_output_timeout: 60m
          command: |
            . .venv/bin/activate
            tox -e py37-test

      - run:
          name: Docs
          no_output_timeout: 60m
          command: |
            . .venv/bin/activate
            tox -e py37-docs

      - store_artifacts:
          path: htmlcov
          destination: coverage-report

      - store_artifacts:
          path: dist/docs
          destination: documentation


workflows:
  version: 2

  build:
    jobs:
      - build-3.8
      - build-3.7
